"""Argilla deployment bootstrap utility.

Four independent operations, run separately:

  --generate-secrets   Generate ~/.archi/secrets/argilla_{api_key,auth_secret,owner_password}.txt
  --export-env         Materialize ~/.archi/argilla.env (sourced by docker-compose).
                       Argilla's entrypoint reads raw USERNAME/PASSWORD/API_KEY env vars;
                       Docker's `_FILE` suffix isn't recognized by their bootstrap script,
                       so we have to inline the values.
  --create-workspace   Create the "archi" workspace via the Argilla SDK
  --create-users FILE  Create one evaluator user per non-empty line in FILE
                       (each line: ``username[,full_name][,email]``)

Run from the repo root:

    python scripts/bootstrap_argilla.py --generate-secrets
    python scripts/bootstrap_argilla.py --export-env
    python scripts/bootstrap_argilla.py --create-workspace
    python scripts/bootstrap_argilla.py --create-users argilla/evaluators.txt
"""

from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path

SECRETS_DIR = Path(os.environ.get("ARCHI_DIR", Path.home() / ".archi")) / "secrets"
SECRETS_DIR.mkdir(parents=True, exist_ok=True)

SECRET_FILES = {
    "argilla_api_key.txt": 32,
    "argilla_auth_secret.txt": 32,
    "argilla_owner_password.txt": 24,
}


def generate_secrets(force: bool) -> int:
    created, skipped = [], []
    for filename, num_bytes in SECRET_FILES.items():
        path = SECRETS_DIR / filename
        if path.exists() and not force:
            skipped.append(path.name)
            continue
        path.write_text(secrets.token_hex(num_bytes))
        path.chmod(0o600)
        created.append(path.name)
    print(f"Created: {created or '(none)'}")
    if skipped:
        print(f"Skipped (already exist; use --force to overwrite): {skipped}")
    print(f"Location: {SECRETS_DIR}")
    return 0


def _read_secret(name: str) -> str:
    path = SECRETS_DIR / name
    if not path.exists():
        print(f"ERROR: missing {path}. Run --generate-secrets first.", file=sys.stderr)
        sys.exit(2)
    return path.read_text().strip()


def export_env() -> int:
    """Materialize ~/.archi/argilla.env from the .txt secret files.

    Argilla 2.x's start_argilla_server.sh checks raw USERNAME/PASSWORD/API_KEY
    env vars; Docker's `_FILE` indirection is NOT supported by that script, so
    we have to inline the values for the docker-compose stack to bootstrap the
    owner account.
    """
    env_path = SECRETS_DIR.parent / "argilla.env"
    lines = [
        "# Auto-generated by scripts/bootstrap_argilla.py --export-env. Do not commit.",
        "USERNAME=owner",
        f"PASSWORD={_read_secret('argilla_owner_password.txt')}",
        f"API_KEY={_read_secret('argilla_api_key.txt')}",
        f"ARGILLA_AUTH_SECRET_KEY={_read_secret('argilla_auth_secret.txt')}",
        "WORKSPACE=archi",
        "",
    ]
    env_path.write_text("\n".join(lines))
    env_path.chmod(0o600)
    print(f"Wrote {env_path} (mode 0600)")
    print("docker-compose will source this file on its next `up -d`.")
    return 0


def _client():
    try:
        import argilla as rg  # pyright: ignore[reportMissingImports]
    except ImportError:
        print(
            "ERROR: the 'argilla' package is required. "
            "Install it with: pip install 'argilla>=2.5,<3'",
            file=sys.stderr,
        )
        sys.exit(2)

    api_url = os.environ.get("ARGILLA_API_URL", "http://localhost:6900")
    api_key = os.environ.get("ARGILLA_API_KEY") or _read_secret("argilla_api_key.txt")
    return rg.Argilla(api_url=api_url, api_key=api_key)


def create_workspace(name: str) -> int:
    import argilla as rg  # pyright: ignore[reportMissingImports]

    client = _client()
    existing = client.workspaces(name=name)
    if existing is not None:
        print(f"Workspace '{name}' already exists.")
        return 0

    ws = rg.Workspace(name=name)
    ws.create()
    print(f"Created workspace: {name}")
    return 0


def create_users(roster_path: Path, workspace: str) -> int:
    import argilla as rg  # pyright: ignore[reportMissingImports]

    if not roster_path.exists():
        print(f"ERROR: roster file not found: {roster_path}", file=sys.stderr)
        return 2

    client = _client()
    ws = client.workspaces(name=workspace)
    if ws is None:
        print(
            f"ERROR: workspace '{workspace}' does not exist. Run --create-workspace first.",
            file=sys.stderr,
        )
        return 2

    created = []
    for line in roster_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = [f.strip() for f in line.split(",")]
        username = fields[0]
        first_name = fields[1] if len(fields) > 1 and fields[1] else username
        if client.users(username=username) is not None:
            print(f"User '{username}' already exists; skipping.")
            continue
        password = secrets.token_urlsafe(16)
        user = rg.User(
            username=username,
            first_name=first_name,
            role="annotator",
            password=password,
        )
        user.create()
        ws.add_user(user)
        created.append((username, password))
        print(f"Created user: {username} (password printed below; record it now)")

    if created:
        print("\n=== TEMPORARY PASSWORDS — distribute securely, then ask each user to rotate ===")
        for username, password in created:
            print(f"  {username}: {password}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--generate-secrets", action="store_true",
                        help="Generate Argilla secrets at ~/.archi/secrets/")
    parser.add_argument("--export-env", action="store_true",
                        help="Materialize ~/.archi/argilla.env for docker-compose")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing secrets (use with --generate-secrets)")
    parser.add_argument("--create-workspace", action="store_true",
                        help="Create the 'archi' workspace via Argilla SDK")
    parser.add_argument("--workspace", default="archi",
                        help="Workspace name (default: archi)")
    parser.add_argument("--create-users", metavar="ROSTER",
                        help="Roster file: one user per line, username[,full_name][,email]")
    args = parser.parse_args()

    if args.generate_secrets:
        return generate_secrets(force=args.force)
    if args.export_env:
        return export_env()
    if args.create_workspace:
        return create_workspace(args.workspace)
    if args.create_users:
        return create_users(Path(args.create_users), args.workspace)

    parser.print_help()
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
