# syntax=docker/dockerfile:1
# base-image-pin: dev-4314ac4 (managed by update_service_base_images.py)
FROM ghcr.io/fasrc/a2rchi-pytorch-base@sha256:c29c6e8b4262736e3a5d3d47756b0d483db88254a91b16932d37f498bc704b5e 
RUN mkdir -p /root/archi
WORKDIR /root/archi

COPY LICENSE LICENSE


RUN apt-get update && apt-get install -y \
    nvidia-utils-550 \
    libnvidia-compute-550 \
    && rm -rf /var/lib/apt/lists/*

COPY archi_code src
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "src/bin/service_mailbox.py"]
