# syntax=docker/dockerfile:1
FROM ghcr.io/fasrc/a2rchi-python-base:v2026.08.0 
RUN mkdir -p /root/archi
WORKDIR /root/archi

COPY LICENSE LICENSE

COPY archi_code src
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "src/bin/service_redmine.py"]
