# syntax=docker/dockerfile:1
FROM ghcr.io/fasrc/a2rchi-pytorch-base:dev-4314ac4 
RUN mkdir -p /root/archi
WORKDIR /root/archi

COPY LICENSE LICENSE


RUN apt-get update && apt-get install -y \
    nvidia-utils-550 \
    libnvidia-compute-550 \
    && rm -rf /var/lib/apt/lists/*

COPY archi_code src
COPY configs configs
COPY pyproject.toml pyproject.toml
COPY weblists weblists
RUN pip install --upgrade pip && pip install .

CMD ["python", "-u", "src/bin/service_mailbox.py"]
