"""Streamed chain-of-thought must never reach the user as an answer (issue #122).

PR #121 (issue #84) sanitized the stored/final answer. The live display still
leaked: on a Qwen-style provider the chat template pre-fills the ``<think>``
opener, so the model streams reasoning first and closes it with an orphan
``</think>``. Until that tag arrives ``_parse_thinking_content()`` has nothing to
strip, so the reasoning *is* the visible content and is emitted as a ``text``
event. The chat layer forwards only truthy chunks, so a later empty result cannot
retract what already reached the screen.

The gate holds visible emission on a thinking-enabled provider until the closing
tag decides what the accumulated text is. These tests pin both stream paths, the
over-suppression guard (a non-thinking provider still streams incrementally), and
the error exits, where held text is discarded rather than flushed.

See ``openspec/changes/fix-issue-122-streaming-think-leak/design.md``.
"""

from __future__ import annotations

import asyncio
from typing import Any, Dict, List, Optional
from unittest.mock import MagicMock

import pytest
from langchain_core.messages import AIMessage, AIMessageChunk, HumanMessage
from langgraph.errors import GraphRecursionError

from src.archi.pipelines.agents.base_react import BaseReActAgent

#: The empty-answer placeholder PR #121 deliberately installed. An orphan-only
#: stream strips to empty and lands here; this change does not touch that.
PLACEHOLDER = "No answer generated by the agent."

#: A vLLM (OpenAI-compatible) context-length overflow, the phrasing the detector
#: recognises. Reused from `tests/unit/test_react_agent_context_overflow.py`.
OVERFLOW_MSG = (
    "You passed 102420 input tokens and requested 0 output tokens. However, the "
    "model's context length is only 32768, resulting in a maximum input length of "
    "32768. Please reduce the length of the input messages."
)


def _config(enable_thinking: Any, provider: str = "local") -> Dict[str, Any]:
    """A chat_app config whose ``provider`` declares ``enable_thinking``.

    ``None`` leaves the key out entirely, which is the unset deployment.
    """
    block: Dict[str, Any] = {}
    if enable_thinking is not None:
        block = {
            "extra_kwargs": {
                "extra_body": {
                    "chat_template_kwargs": {"enable_thinking": enable_thinking}
                }
            }
        }
    return {"services": {"chat_app": {"providers": {provider: block}}}}


THINKING_ON = _config(True)
THINKING_OFF = _config(False)
THINKING_UNSET = _config(None)


class _TestableAgent(BaseReActAgent):
    """Subclass that skips LLM/prompt/LangGraph init so the stream paths run alone.

    Modelled on the harness in ``tests/unit/test_react_agent_context_overflow.py``.
    The wrap-up generators are stubbed out so an error exit builds its canned
    message instead of calling a model.
    """

    def __init__(
        self, config: Optional[Dict[str, Any]] = None, provider: str = "local"
    ) -> None:
        self.config = config or {}
        self.archi_config = {}
        self.dm_config = {}
        self.pipeline_config = {}
        self.agent_spec = None
        self.default_provider = provider
        self.default_model = "a-model"
        self.selected_tool_names = []
        self._active_memory = None
        self._tool_budgets_cache = None
        self._static_tools = None
        self._mcp_tools = None
        self._active_tools = []
        self._static_middleware = None
        self._active_middleware = []
        self.agent = MagicMock()
        self.agent_llm = MagicMock()
        self.agent_prompt = "test prompt"
        self.mcp_client = None

    def _prepare_agent_inputs(self, **kwargs: Any) -> Dict[str, Any]:
        return {"messages": [HumanMessage(content="how do I do X?")]}

    def _generate_wrap_up_message(self, **kwargs: Any):
        return None

    async def _generate_wrap_up_message_async(self, **kwargs: Any):
        return None


def _deltas(*texts: str) -> List[AIMessageChunk]:
    """Streamed chunks, whose content the agent treats as deltas."""
    return [AIMessageChunk(content=text) for text in texts]


# --- driving both stream paths from one test body (2.1) ---------------------


def _run_sync(agent: _TestableAgent, events, error: Optional[Exception] = None):
    def _stream(*args: Any, **kwargs: Any):
        for event in events:
            yield event
        if error is not None:
            raise error

    agent.agent.stream = _stream
    return list(agent.stream())


def _run_async(agent: _TestableAgent, events, error: Optional[Exception] = None):
    async def _astream(*args: Any, **kwargs: Any):
        for event in events:
            yield event
        if error is not None:
            raise error

    agent.agent.astream = _astream

    async def _collect():
        return [output async for output in agent.astream()]

    return asyncio.run(_collect())


#: Both stream paths share one decision function, so every behavioral test runs
#: against both and they cannot drift.
both_paths = pytest.mark.parametrize(
    "run", [_run_sync, _run_async], ids=["stream", "astream"]
)


def _texts(outputs) -> List[str]:
    """The answers of the visible ``text`` events, in order."""
    return [o.answer for o in outputs if o.metadata.get("event_type") == "text"]


def _final(outputs):
    """The terminal output of the stream."""
    finals = [o for o in outputs if o.final]
    assert finals, "the stream produced no final output"
    return finals[-1]


def _assert_no_reasoning_visible(outputs) -> None:
    """No visible event carries reasoning, and none carries a bare closing tag."""
    for text in _texts(outputs):
        assert "reasoning" not in text
        assert "</think>" not in text


# --- the leak itself, both paths (2.2, 2.3) ---------------------------------


@both_paths
def test_reasoning_is_never_emitted_before_the_closing_tag(run):
    """The answer streams, the reasoning that preceded it does not."""
    agent = _TestableAgent(THINKING_ON)
    outputs = run(
        agent, _deltas("some reasoning", " continues", "</think>", "\n\nThe answer")
    )

    _assert_no_reasoning_visible(outputs)
    assert _texts(outputs) == ["The answer"]
    assert _final(outputs).answer == "The answer"


# --- orphan-only: nothing visible, and PR #121's placeholder stands (2.4) ---


@both_paths
def test_orphan_only_stream_shows_nothing_and_keeps_the_placeholder(run):
    """Reasoning then a closing tag, then the stream ends.

    The final answer is the placeholder the empty-answer fallback substitutes,
    not an empty string — that contract belongs to PR #121.
    """
    agent = _TestableAgent(THINKING_ON)
    outputs = run(agent, _deltas("some reasoning", "</think>"))

    _assert_no_reasoning_visible(outputs)
    assert _texts(outputs) == []
    assert _final(outputs).answer == PLACEHOLDER


# --- the over-suppression guard: this passes today too (2.5) ----------------


@both_paths
@pytest.mark.parametrize(
    "config", [THINKING_OFF, THINKING_UNSET], ids=["disabled", "unset"]
)
def test_a_non_thinking_provider_still_streams_incrementally(run, config):
    """A provider that cannot emit reasoning streams chunk-by-chunk, as before."""
    agent = _TestableAgent(config)
    outputs = run(agent, _deltas("The ", "quick ", "answer"))

    assert _texts(outputs) == ["The", "The quick", "The quick answer"]
    assert _final(outputs).answer == "The quick answer"


# --- a thinking provider that never closes its block (2.6) ------------------


@both_paths
def test_an_answer_with_no_closing_tag_is_held_to_the_final_event(run):
    """The accepted cost of a config-keyed gate: the answer arrives at once.

    Nothing is lost on a stream that completes; only the incremental display is.
    """
    agent = _TestableAgent(THINKING_ON)
    outputs = run(agent, _deltas("The ", "quick ", "answer"))

    assert _texts(outputs) == []
    assert _final(outputs).answer == "The quick answer"


# --- the last-full-AI-message branch, which chunks alone never reach (2.7) --


@both_paths
def test_no_reasoning_leaks_on_the_full_message_branch(run):
    """A terminal FULL AI message populates ``all_messages``.

    A chunk-only stream leaves that list empty, so the final answer comes from
    the ``accumulated_content`` fallback and the "last full AI message" branch
    goes untested. This drives that branch instead.
    """
    agent = _TestableAgent(THINKING_ON)
    outputs = run(
        agent,
        [
            *_deltas("some reasoning"),
            AIMessage(content="some reasoning</think>\n\nThe answer"),
        ],
    )

    _assert_no_reasoning_visible(outputs)
    assert _texts(outputs) == ["The answer"]
    final = _final(outputs)
    assert final.answer == "The answer"
    assert "reasoning" not in final.answer


@both_paths
def test_a_full_message_of_pure_reasoning_yields_the_placeholder(run):
    """The same branch when the model produced reasoning and no answer."""
    agent = _TestableAgent(THINKING_ON)
    outputs = run(agent, [AIMessage(content="some reasoning</think>")])

    _assert_no_reasoning_visible(outputs)
    assert _final(outputs).answer == PLACEHOLDER


# --- error exits discard held text rather than flushing it (4.1, 4.2) -------


@both_paths
def test_held_text_is_discarded_on_a_recursion_limit_exit(run):
    """Decision 7: undecided text is reasoning, and is dropped, never shown."""
    agent = _TestableAgent(THINKING_ON)
    outputs = run(
        agent,
        _deltas("some reasoning", " continues"),
        error=GraphRecursionError("recursion limit reached"),
    )

    _assert_no_reasoning_visible(outputs)
    assert _texts(outputs) == []

    final = _final(outputs)
    assert final.metadata.get("recursion_exhausted") is True
    assert "reasoning" not in final.answer


@both_paths
def test_held_text_is_discarded_on_a_context_overflow_exit(run):
    """The overflow exit keeps its own output, and shows no held reasoning."""
    agent = _TestableAgent(THINKING_ON)
    # Every retry overflows too, so the handler takes its fallback-message path.
    agent.agent.invoke = MagicMock(side_effect=Exception(OVERFLOW_MSG))

    outputs = run(
        agent,
        _deltas("some reasoning", " continues"),
        error=Exception(OVERFLOW_MSG),
    )

    _assert_no_reasoning_visible(outputs)
    assert _texts(outputs) == []

    final = _final(outputs)
    assert final.metadata.get("error_type") == "context_overflow"
    assert "reasoning" not in final.answer


@both_paths
def test_a_non_overflow_error_still_propagates(run):
    """The gate must not swallow an unrelated failure."""
    agent = _TestableAgent(THINKING_ON)

    with pytest.raises(ValueError):
        run(agent, _deltas("some reasoning"), error=ValueError("unrelated"))
