"""Unit tests for BaseReActAgent._parse_thinking_content orphan-tag handling.

Covers issue #84: some models (e.g. Qwen3 in certain streaming modes) emit
chain-of-thought reasoning terminated by an *orphan* ``</think>`` closing tag
with no matching opening ``<think>``. The original balanced-pair regex left that
reasoning (and the bare closing tag) in the visible answer. These tests pin the
contract in ``specs/react-thinking-sanitization/spec.md``: orphan-closed
reasoning is stripped into the thinking channel and never leaks into visible
output.
"""

from __future__ import annotations

from langchain_core.messages import AIMessage

from src.archi.pipelines.agents.base_react import BaseReActAgent


def _parse(text: str):
    """Call the parser with a minimal dummy ``self`` (the method uses no state)."""
    return BaseReActAgent._parse_thinking_content(object(), text)


def _agent() -> BaseReActAgent:
    """A BaseReActAgent with just enough state to build outputs (no __init__)."""
    agent = BaseReActAgent.__new__(BaseReActAgent)
    agent._active_memory = (
        None  # backing field for the read-only active_memory property
    )
    return agent


def test_balanced_pair_regression():
    visible, thinking = _parse("<think>r</think>\n\nAns")
    assert visible == "Ans"
    assert "r" in thinking
    assert "</think>" not in visible and "<think>" not in visible


def test_single_orphan_closing_tag():
    visible, thinking = _parse("reasoning\n</think>\n\nAns")
    assert visible == "Ans"
    assert "reasoning" in thinking
    assert "</think>" not in visible and "<think>" not in visible


def test_multiple_orphan_closing_tags():
    visible, thinking = _parse("t1\n</think>\n\nt2\n</think>\n\nt3\n</think>\n\nAns")
    assert visible == "Ans"
    assert "</think>" not in visible and "<think>" not in visible


def test_no_tags_unchanged():
    visible, thinking = _parse("Just an answer.")
    assert visible == "Just an answer."
    assert thinking == ""


def test_empty_input():
    assert _parse("") == ("", "")


# --- Codex review (PR #121): the strip must also cover the stored-answer paths
# that bypass _parse_thinking_content — _build_output_from_messages, used by the
# non-streaming invoke() path (finding 3) and the stream empty-answer fallback
# (finding 2). These pin that the final/stored answer is sanitized there too.


def test_build_output_strips_orphan_think():
    # Non-streaming invoke() builds the answer here; it must strip orphan </think>
    # instead of storing the raw message.
    out = _agent()._build_output_from_messages(
        [AIMessage(content="secret reasoning\n</think>\n\nFinal answer.")]
    )
    assert out.answer == "Final answer."
    assert "</think>" not in out.answer
    assert "secret reasoning" not in out.answer


def test_build_output_orphan_only_does_not_leak_reasoning():
    # Orphan-only output (reasoning + </think>, no answer) strips to empty — it must
    # NOT fall back to the raw reasoning; a safe placeholder is used instead.
    out = _agent()._build_output_from_messages(
        [AIMessage(content="only chain of thought\n</think>")]
    )
    assert "</think>" not in out.answer
    assert "chain of thought" not in out.answer
    assert out.answer == "No answer generated by the agent."


def test_build_output_strips_balanced_think():
    out = _agent()._build_output_from_messages(
        [AIMessage(content="<think>r</think>Answer here.")]
    )
    assert out.answer == "Answer here."
    assert "<think>" not in out.answer and "</think>" not in out.answer
