"""Provenance is tied to the source-copy/build path.

Covers the "Deployment records the source commit" spec requirement. The write lives
in ``copy_source_code`` (the single point that materialises the source the image is
built from) rather than in ``prepare_deployment_files``, so:

* a rebuild that copies source always refreshes ``SOURCE_COMMIT`` (``restart`` with the
  default rebuild), and
* a run that does not rebuild (``restart --no-build``) leaves it untouched — the recorded
  commit reflects the code actually running in the image.

The commit resolver is patched so assertions do not depend on the runner's git state.
"""

import sys
from pathlib import Path
from types import ModuleType
from unittest.mock import MagicMock

from jinja2 import Environment

from src.cli.managers import source_version, templates_manager
from src.cli.managers.templates_manager import TemplateContext, TemplateManager
from src.cli.utils.service_builder import ServiceBuilder


def _manager():
    return TemplateManager(Environment(), verbosity=0)


def _plan(base_dir):
    return ServiceBuilder.build_compose_config(
        name="t",
        verbosity=0,
        base_dir=base_dir,
        enabled_services=["chatbot"],
    )


def _context(base_dir, **options):
    return TemplateContext(
        plan=_plan(base_dir),
        config_manager=None,
        secrets_manager=None,
        options=dict(options),
    )


def _fake_repo(tmp_path):
    repo = tmp_path / "checkout"
    (repo / "src").mkdir(parents=True)
    (repo / "src" / "archi.py").write_text("print('hi')\n")
    (repo / "pyproject.toml").write_text("[project]\nname='archi'\n")
    (repo / "LICENSE").write_text("MIT\n")
    return repo


def _install_repo_info(monkeypatch, repo):
    # ``_repository_info`` is generated by setup.py at install time and gitignored,
    # so it is absent in a fresh checkout (e.g. CI). Inject a fake at the import seam
    # instead of patching an attribute on a module that may not exist. Cover both
    # ``from src.cli.utils import _repository_info`` (needs the sys.modules entry) and
    # ``import src.cli.utils._repository_info`` + attribute access (needs the parent
    # package attribute too).
    import src.cli.utils as utils_pkg

    fake_info = ModuleType("src.cli.utils._repository_info")
    fake_info.REPO_PATH = str(repo)
    monkeypatch.setitem(sys.modules, "src.cli.utils._repository_info", fake_info)
    monkeypatch.setattr(utils_pkg, "_repository_info", fake_info, raising=False)


def test_copy_source_code_writes_source_commit(monkeypatch, tmp_path):
    repo = _fake_repo(tmp_path)
    base_dir = tmp_path / "deploy"
    base_dir.mkdir()

    _install_repo_info(monkeypatch, repo)
    monkeypatch.setattr(
        source_version,
        "resolve_source_commit",
        lambda repo_root=None: "936a52f8-dirty",
    )

    _manager().copy_source_code(base_dir)

    assert (base_dir / "archi_code").is_dir()
    assert (base_dir / "SOURCE_COMMIT").read_text().strip() == "936a52f8-dirty"


def test_copy_source_code_ties_commit_to_copied_repo_root(monkeypatch, tmp_path):
    repo = _fake_repo(tmp_path)
    base_dir = tmp_path / "deploy"
    base_dir.mkdir()

    _install_repo_info(monkeypatch, repo)
    spy = MagicMock(return_value="deadbeef")
    monkeypatch.setattr(templates_manager, "write_source_commit", spy)

    _manager().copy_source_code(base_dir)

    spy.assert_called_once()
    args, kwargs = spy.call_args
    # Provenance is resolved from the same checkout the source was copied from.
    assert Path(kwargs.get("repo_root", args[1] if len(args) > 1 else None)) == repo


def test_stage_source_copy_runs_when_build_enabled(monkeypatch, tmp_path):
    called = {}
    monkeypatch.setattr(
        TemplateManager,
        "copy_source_code",
        lambda self, base_dir: called.setdefault("base_dir", base_dir),
    )

    ctx = _context(tmp_path)  # build defaults to True
    _manager()._stage_source_copy(ctx)

    assert called.get("base_dir") == tmp_path


def test_stage_source_copy_skips_when_build_disabled(monkeypatch, tmp_path):
    called = {}
    monkeypatch.setattr(
        TemplateManager,
        "copy_source_code",
        lambda self, base_dir: called.setdefault("base_dir", base_dir),
    )

    ctx = _context(tmp_path, build=False)
    _manager()._stage_source_copy(ctx)

    assert "base_dir" not in called
    assert not (tmp_path / "SOURCE_COMMIT").exists()


def test_context_build_defaults_true_and_reads_option(tmp_path):
    assert _context(tmp_path).build is True
    assert _context(tmp_path, build=False).build is False


def test_the_source_copy_falls_back_to_the_package_root_not_to_this_file(
    monkeypatch, tmp_path
):
    """Without a recorded checkout the copy must still land on a real tree.

    ``_repository_info`` is written by ``setup.py`` at install time, so it is absent
    whenever archi runs from a source tree that was never installed. The fallback set
    ``repo_root = Path(__file__).resolve()`` -- the module *file*, not a directory -- so
    ``repo_root / "src"`` was ``.../templates_manager.py/src``, which cannot exist, and
    ``copy_source_code`` raised ``FileNotFoundError`` (``templates_manager.py:1198``).

    That is not a harmless error, because of where it happens. ``_stage_source_copy``
    runs from ``prepare_deployment_files`` (``cli_main.py:923``), *below*
    ``remove_existing_deployment()`` (``cli_main.py:906``). So ``create --force`` and
    ``evaluate --force`` destroyed the operator's running deployment and only then died
    staging the source -- deterministically, every time, on the one install shape the
    base-image preflight is allowed to pass without a recorded checkout
    (fasrc/archi#436 review).

    The fallback now derives the same package root the preflight's ``TEMPLATE_DIR``
    does, so the two agree about which tree is being deployed.
    """
    copied = []
    # `None` in sys.modules makes `import src.cli.utils._repository_info` raise, in both
    # environments: absent in a bare worktree, present after any `pip install`.
    monkeypatch.setitem(sys.modules, "src.cli.utils._repository_info", None)
    monkeypatch.setattr(
        templates_manager.shutil, "copytree", lambda s, d: copied.append(Path(s))
    )
    monkeypatch.setattr(
        templates_manager.shutil, "copyfile", lambda s, d: copied.append(Path(s))
    )
    monkeypatch.setattr(templates_manager, "write_source_commit", MagicMock())

    base_dir = tmp_path / "deploy"
    base_dir.mkdir()

    _manager().copy_source_code(base_dir)

    package_root = Path(templates_manager.__file__).resolve().parents[3]
    assert copied == [
        package_root / "src",
        package_root / "pyproject.toml",
        package_root / "LICENSE",
    ], "the fallback must resolve a directory, not the module file"


def test_the_source_copy_fallback_agrees_with_the_preflight_template_dir(monkeypatch):
    """One package root, or the preflight probes a tree the build never copies.

    ``base_image_preflight.TEMPLATE_DIR`` and this fallback are two independent
    ``__file__`` derivations of the same thing. If they drift apart the preflight
    establishes a base image for a tree the source copy does not ship, which is the
    fail-open the preflight exists to remove -- so pin them together rather than trust
    two parent-hop counts to stay in step.
    """
    from src.cli.managers import base_image_preflight

    assert (
        templates_manager._package_repo_root()
        .joinpath("src", "cli", "templates", "dockerfiles")
        .resolve()
        == base_image_preflight.TEMPLATE_DIR.resolve()
    )
