"""Base-image requirements files are derived artifacts, not sources.

``scripts/dev/build_docker_images.sh`` regenerates both tracked requirements
files on every base-image publish by concatenating a header file with
``requirements/requirements-base.txt``. A tracked copy that differs from that
concatenation is stale by definition: the next publish will overwrite it, so a
divergent copy in git is misleading rather than authoritative. This guard fails
the suite whenever that invariant breaks, independently per file, so drift is
caught before someone "fixes" it by hand-editing the generated file.
"""

import difflib
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

GENERATED_PAIRS = {
    "base-python-image": (
        REPO_ROOT / "requirements" / "cpu-requirementsHEADER.txt",
        REPO_ROOT
        / "src"
        / "cli"
        / "templates"
        / "dockerfiles"
        / "base-python-image"
        / "requirements.txt",
    ),
    "base-pytorch-image": (
        REPO_ROOT / "requirements" / "gpu-requirementsHEADER.txt",
        REPO_ROOT
        / "src"
        / "cli"
        / "templates"
        / "dockerfiles"
        / "base-pytorch-image"
        / "requirements.txt",
    ),
}

BASE_REQUIREMENTS = REPO_ROOT / "requirements" / "requirements-base.txt"


def _unified_diff(expected: bytes, actual: bytes, generated_path: Path) -> str:
    expected_lines = expected.decode("utf-8", errors="replace").splitlines(
        keepends=True
    )
    actual_lines = actual.decode("utf-8", errors="replace").splitlines(keepends=True)
    diff = "".join(
        difflib.unified_diff(
            expected_lines,
            actual_lines,
            fromfile="expected (header + requirements-base.txt)",
            tofile=str(generated_path),
        )
    )
    return diff


class TestGeneratedRequirementsMatchGenerator:
    """These files are derived artifacts regenerated by
    ``scripts/dev/build_docker_images.sh`` on every base-image publish, so a
    tracked copy that differs from that regeneration is stale by definition.
    """

    @pytest.mark.parametrize("image_name", sorted(GENERATED_PAIRS))
    def test_generated_requirements_match_header_plus_base(self, image_name):
        """The tracked file must be byte-identical to the generator's output.

        Comparison is on raw bytes, not decoded text: ``read_text()`` performs
        universal-newline translation and would silently accept a ``\\r\\n``
        file that the generator would still rewrite.
        """
        header_path, generated_path = GENERATED_PAIRS[image_name]
        expected = header_path.read_bytes() + BASE_REQUIREMENTS.read_bytes()
        actual = generated_path.read_bytes()

        assert actual == expected, (
            f"{generated_path.relative_to(REPO_ROOT)} is stale: it no longer matches "
            f"{header_path.relative_to(REPO_ROOT)} + "
            f"{BASE_REQUIREMENTS.relative_to(REPO_ROOT)}. Regenerate it with "
            f"`cat {header_path.relative_to(REPO_ROOT)} "
            f"{BASE_REQUIREMENTS.relative_to(REPO_ROOT)} > "
            f"{generated_path.relative_to(REPO_ROOT)}` "
            "(the same command scripts/dev/build_docker_images.sh runs) rather than "
            "hand-editing the generated file.\n"
            f"{_unified_diff(expected, actual, generated_path)}"
        )
